apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-02T14:00:00Z"
  labels:
    app: influxdb
  name: influxdb
spec:
  ports:
    - name: "8086"
      port: 8087
      targetPort: 8086
  selector:
    app: influxdb
  type: LoadBalancer