apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: "2021-09-02T14:00:00Z"
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: "2021-09-02T14:00:00Z"
      labels:
        io.kompose.network/: "true"
        app: influxdb
    spec:
      containers:
        - env:
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "false"
            - name: INFLUXDB_HTTP_FLUX_ENABLED
              value: "false"
            - name: INFLUXDB_MONITOR_STORE_ENABLED
              value: "FALSE"
            - name: INFLUXDB_REPORTING_DISABLED
              value: "false"
            - name: TZ
              value: Etc/UTC
          image: influxdb:1.8
          livenessProbe:
            exec:
              command:
                - curl
                - http://localhost:8086
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: influxdb
          ports:
            - containerPort: 8086
          resources: { 
            limits: {
              cpu: 100m,
              memory: 100Mi
            },
            requests: {
              cpu: 100m,
              memory: 100Mi
            }}
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-claim0
            - mountPath: /var/lib/influxdb/backup
              name: influxdb-claim1
      restartPolicy: Always
      volumes:
        - name: influxdb-claim0
          persistentVolumeClaim:
            claimName: influxdb-claim0
        - name: influxdb-claim1
          persistentVolumeClaim:
            claimName: influxdb-claim1
status: {}