apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-pv
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/var/"