apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: "2021-09-02T14:00:00Z"
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: "2021-09-02T14:00:00Z"
      labels:
        io.kompose.network/: "true"
        io.kompose.service: mosquitto
    spec:
      containers:
        - env:
            - name: TZ
              value: Etc/UTC
          image: mosquitto
          name: mosquitto
          ports:
            - containerPort: 1883
          resources: { 
            limits: {
              cpu: 100m,
              memory: 100Mi
            },
            requests: {
              cpu: 100m,
              memory: 100Mi
            }
          }
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto-claim0
            - mountPath: /mosquitto/data
              name: mosquitto-claim1
            - mountPath: /mosquitto/log
              name: mosquitto-claim2
            - mountPath: /mosquitto/pwfile
              name: mosquitto-claim3
      restartPolicy: Always
      volumes:
        - name: mosquitto-claim0
          persistentVolumeClaim:
            claimName: mosquitto-claim0
        - name: mosquitto-claim1
          persistentVolumeClaim:
            claimName: mosquitto-claim1
        - name: mosquitto-claim2
          persistentVolumeClaim:
            claimName: mosquitto-claim2
        - name: mosquitto-claim3
          persistentVolumeClaim:
            claimName: mosquitto-claim3
status: {}