apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-02T14:00:00Z"
  labels:
    app: mosquitto
  name: mosquitto
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    app: mosquitto
status:
  loadBalancer: {}
