apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mosquitto/"