apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-02T14:00:00Z"
  labels:
    app: nodered
  name: nodered
spec:
  ports:
    - name: "1880"
      port: 1880
      targetPort: 1880
  selector:
    app: nodered
status:
  loadBalancer: {}
