apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2021-09-02T14:00:00Z"
  labels:
    app: nodered-claim3
  name: nodered-claim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
